language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - python setup.py install
script:
  - tree -f
  - pytest
#after_success:
#  - coveralls