name: Python Deploy

on:
  release:
    types: [published]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install --user --upgrade twine setuptools wheel
    - name: Create Wheels and Upload
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/* -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
